export const SET_PRODUCTS = "PRODUCTS/SET_PRODUCTS";
export const SET_CATEGORIES = "PRODUCTS/SET_CATEGORIES";
export const SELECT_CATEGORY = "PRODUCTS/SELECT_CATEGORY";
export const RESET_CATEGORY = "PRODUCTS/RESET_CATEGORY";
export const SET_SORT_TYPE = "PRODUCTS/SET_SORT_TYPE";
export const SET_SORT_ORDER = "PRODUCTS/SET_SORT_ORDER";
export const CLEAR_SEARCH = "PRODUCTS/CLEAR_SEARCH";
export const SET_SAERCH_VALUE = "PRODUCTS/SET_SAERCH_VALUE";

export const SET_USER = "USER/SET_USER";
export const REMOVE_USER = "USER/REMOVE_USER";

export const SET_LOADING = "LOADING/SET_LOADING";
export const STOP_LOADING = "LOADING/STOP_LOADING";

export const SHOW_ALERT = "ALERT/SHOW_ALERT";
export const HIDE_ALERT = "ALERT/HIDE_ALERT";

export const SET_BASKET_ITEMS = "BASKET/SET_BASKET_ITEMS";
export const SET_TOTAL_COUNT = "BASKET/SET_TOTAL_COUNT";
export const SET_TOTAL_PRICE = "BASKET/SET_TOTAL_PRICE";
export const SET_BADGE_COUNT = "BASKET/SET_BADGE_COUNT";
export const SET_BASKET = "BASKET/SET_BASKET";

export const OPEN_MODAL ="MODAL/OPEN_MODAL"
export const CLOSE_MODAL ="MODAL/CLOSE_MODAL"